# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae21bdfaf6a9dc5d66dc91cc5c8eb57d375dc15a2eed754f337d9a3de2eeabf52bd6ec3df5a7583fb366a3fb4eb61314bf6db7cfc2a243b9ac883bbfc36ab62e

test:
  secret_key_base: 4d66529cac79dfe59befd996f94e999f0144cc4af5d82085c81155a5a23d883804eba8441f0cdd1c638348e1f439f97b90fe9b535299b3f953eca9d2fa5602a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
